version: '3.7'
services:
  postgresql:
    container_name: postgres
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: categories
    ports:
      - "5432:5432"
    networks:
      - app

networks:
  app:
    driver: bridge